"""
Report generation utilities for Googology Wiki analysis tools.
"""

from datetime import datetime
from .io_utils import get_fetch_date


def generate_license_footer(tool_name: str) -> str:
    """
    Generate standard license and attribution footer for reports.
    
    Args:
        tool_name: Name of the tool generating the report
        
    Returns:
        Formatted license footer as markdown string
    """
    return f"""---

## License and Attribution

This analysis contains content from the **Googology Wiki** (googology.fandom.com), which is licensed under the [Creative Commons Attribution-ShareAlike 3.0 Unported License](https://creativecommons.org/licenses/by-sa/3.0/).

- **Original Source**: [Googology Wiki](https://googology.fandom.com)
- **License**: [CC BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/)
- **Attribution**: Content creators and contributors of the Googology Wiki
- **Modifications**: This analysis extracts and reorganizes data from the original wiki content

*Archive fetched: {get_fetch_date()}*  
*Generated by {tool_name}*  
*Analysis date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
"""


def write_markdown_report(file_path: str, content: str) -> None:
    """
    Write markdown content to a file with UTF-8 encoding.
    
    Args:
        file_path: Path to output file
        content: Markdown content to write
    """
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"Report generated: {file_path}")