name: Manual Pipeline Test

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: true
        default: 'main'
        type: string

jobs:
  test-pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 py7zr tiktoken
    
    - name: Create data directory
      run: |
        mkdir -p data
        cd tools
        
    - name: Run fetch tool
      working-directory: tools/fetch
      run: |
        echo "Running fetch.py..."
        python fetch.py
        
    - name: Verify XML file exists
      run: |
        if [ ! -f "data/googology_pages_current.xml" ]; then
          echo "ERROR: XML file not found"
          exit 1
        fi
        echo "✓ XML file exists"
        
    - name: Check XML file size
      run: |
        xml_size=$(stat -c%s "data/googology_pages_current.xml" 2>/dev/null || echo "0")
        if [ "$xml_size" -lt 1000000 ]; then
          echo "ERROR: XML file too small ($xml_size bytes)"
          exit 1
        fi
        echo "✓ XML file size OK ($xml_size bytes)"
        
    - name: Run analysis pipeline
      working-directory: tools
      run: |
        echo "Running dothemall.bash..."
        bash dothemall.bash
        
    - name: Verify output files exist
      run: |
        echo "Checking required output files..."
        
        # Check contributors analysis
        if [ ! -f "tools/contributors/contributors.md" ]; then
          echo "ERROR: contributors.md not found"
          exit 1
        fi
        echo "✓ contributors.md exists"
        
        # Check large pages analysis  
        if [ ! -f "tools/large-pages/large-pages.md" ]; then
          echo "ERROR: large-pages.md not found"
          exit 1
        fi
        echo "✓ large-pages.md exists"
        
        # Check namespace analysis
        if [ ! -f "tools/namespaces/namespaces.md" ]; then
          echo "ERROR: namespaces.md not found"
          exit 1
        fi
        echo "✓ namespaces.md exists"
        
        # Check random page selector
        if [ ! -f "tools/random/index.html" ]; then
          echo "ERROR: random/index.html not found"
          exit 1
        fi
        echo "✓ random/index.html exists"
        
        # Check token analysis
        if [ ! -f "tools/tokens/tokens.md" ]; then
          echo "ERROR: tokens.md not found"
          exit 1
        fi
        echo "✓ tokens.md exists"
        
    - name: Verify file content quality
      run: |
        echo "Checking file content quality..."
        
        # Check contributors.md has data
        contrib_lines=$(wc -l < "tools/contributors/contributors.md")
        if [ "$contrib_lines" -lt 50 ]; then
          echo "ERROR: contributors.md too short ($contrib_lines lines)"
          exit 1
        fi
        echo "✓ contributors.md has $contrib_lines lines"
        
        # Check large-pages.md has data
        pages_lines=$(wc -l < "tools/large-pages/large-pages.md")
        if [ "$pages_lines" -lt 50 ]; then
          echo "ERROR: large-pages.md too short ($pages_lines lines)"
          exit 1
        fi
        echo "✓ large-pages.md has $pages_lines lines"
        
        # Check namespaces.md has data
        ns_lines=$(wc -l < "tools/namespaces/namespaces.md")
        if [ "$ns_lines" -lt 30 ]; then
          echo "ERROR: namespaces.md too short ($ns_lines lines)"
          exit 1
        fi
        echo "✓ namespaces.md has $ns_lines lines"
        
        # Check random/index.html has links
        if ! grep -q "googology.fandom.com" "tools/random/index.html"; then
          echo "ERROR: random/index.html missing wiki links"
          exit 1
        fi
        echo "✓ random/index.html contains wiki links"
        
        # Check tokens.md has data
        tokens_lines=$(wc -l < "tools/tokens/tokens.md")
        if [ "$tokens_lines" -lt 30 ]; then
          echo "ERROR: tokens.md too short ($tokens_lines lines)"
          exit 1
        fi
        echo "✓ tokens.md has $tokens_lines lines"
        
    - name: Check for Python errors in logs
      run: |
        echo "Checking for Python errors..."
        
        # Check if any analysis tool failed
        if grep -i "error\|traceback\|exception" tools/contributors/contributors.md 2>/dev/null; then
          echo "ERROR: Found error messages in contributors.md"
          exit 1
        fi
        
        if grep -i "error\|traceback\|exception" tools/large-pages/large-pages.md 2>/dev/null; then
          echo "ERROR: Found error messages in large-pages.md"
          exit 1
        fi
        
        if grep -i "error\|traceback\|exception" tools/namespaces/namespaces.md 2>/dev/null; then
          echo "ERROR: Found error messages in namespaces.md"
          exit 1
        fi
        
        if grep -i "error\|traceback\|exception" tools/tokens/tokens.md 2>/dev/null; then
          echo "ERROR: Found error messages in tokens.md"
          exit 1
        fi
        
        echo "✓ No error messages found in output files"
        
    - name: Test complete
      run: |
        echo "🎉 All tests passed!"
        echo "✓ fetch.py completed successfully"
        echo "✓ dothemall.bash completed successfully"  
        echo "✓ All required output files exist"
        echo "✓ File content quality checks passed"
        echo "✓ No Python errors detected"
        echo ""
        echo "Pipeline test PASSED ✅"